FROM xosproject/xos-synchronizer-base:candidate

ADD . /opt/xos/synchronizers/openstack

ENTRYPOINT []

WORKDIR "/opt/xos/synchronizers/openstack"

CMD bash -c "update-ca-certificates; cd /opt/xos/synchronizers/openstack; ./run-from-api.sh"
